# Do not forget to create the .env file (see template)
# before using this container!

services:
    space-api-svc:
        restart: always
        build: .
        env_file:
            - .env
        ports:
            - $PORT:8080
